package UI;

import Java.DatabaseConnector;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

/**
 * @author ma19peza
 */
public class Login extends javax.swing.JFrame {

    private String username = "1231";
    private char[] password;

    /**
     * Creates new form Login
     */
    //Constructer takes in a user and sets the private user varible to it
    public Login() {
        //creates the JFrame and populates it with content
        initComponents();
        //Sets the JFrame to the center of the users screen
        this.setLocationRelativeTo(null);
        lblErr.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBG = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        usernameUnderline = new javax.swing.JSeparator();
        passwordUnderline = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        lblErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelBG.setBackground(new java.awt.Color(153, 153, 153));
        PanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username");
        lblUsername.setFocusable(false);
        PanelBG.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, -1, -1));

        lblPassword.setText("Password");
        lblPassword.setFocusable(false);
        PanelBG.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 104, 63, -1));

        txtUsername.setBackground(new java.awt.Color(153, 153, 153));
        txtUsername.setBorder(null);
        txtUsername.setOpaque(false);
        PanelBG.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 162, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        PanelBG.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 173, 39));

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        PanelBG.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 19, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SAC Rowing Club Logo.jpg"))); // NOI18N
        lblLogo.setText("PLACEHOLDER");
        PanelBG.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 170, 170));

        usernameUnderline.setForeground(new java.awt.Color(255, 255, 255));
        PanelBG.add(usernameUnderline, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 173, 10));

        passwordUnderline.setForeground(new java.awt.Color(255, 255, 255));
        PanelBG.add(passwordUnderline, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, 173, 10));

        txtPassword.setBackground(new java.awt.Color(153, 153, 153));
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        PanelBG.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 127, 162, -1));

        lblErr.setText("Incorrect Username/Password");
        PanelBG.add(lblErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Retreaves the data the user entered and calls the database to validify the data and allow the user to login
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        lblErr.setVisible(false);
        username = txtUsername.getText();
        password = txtPassword.getPassword();

        DatabaseConnector db = new DatabaseConnector();
        if (db.checkUsername(username) && db.checkPassword(username, password)) {
            Dashboard dash = new Dashboard(db.getUser(username), db);

            this.setVisible(false);
            dash.setVisible(true);
            //if the check fails the program will display an error message and not login
        } else {
            lblErr.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    //Opens the help file
    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        try {
            File helpFile = new File("src/Resources/HTML/Help.html");
            Desktop.getDesktop().open(helpFile);
        } catch (IOException e) {
            System.out.println("Error\n" + e);
        }
    }//GEN-LAST:event_btnHelpActionPerformed
    //Returns the private String username

    public String getusername() {
        return username;
    }

    /**
     * @param args the command line arguments
     */
    //Opens and instantiates this screen
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBG;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblErr;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JSeparator passwordUnderline;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JSeparator usernameUnderline;
    // End of variables declaration//GEN-END:variables
}
