package UI;

import Java.DatabaseConnector;
import Models.Users;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;

/**
 * @author ma19peza
 */
public class SetBoatScreen extends javax.swing.JFrame {

    Users user;
    Dashboard dash;
    DatabaseConnector db = new DatabaseConnector();

    /**
     * Creates new form SetBoatScreen
     *
     * @param userN
     * @param dashN
     */
    //Constructer takes in a user and a dashborad and sets the private user and dashboard varible respectivly to it
    public SetBoatScreen(Users userN, Dashboard dashN) {
        //creates the JFrame and populates it with content
        initComponents();
        //Sets the JFrame to the center of the users screen
        this.setLocationRelativeTo(null);
        user = userN;
        dash = dashN;
        //Calls the helper methode to populate the comboBox
        populateCBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBG = new javax.swing.JPanel();
        lblSetBoat = new javax.swing.JLabel();
        cBoxSetBoat = new javax.swing.JComboBox();
        lblInSlot = new javax.swing.JLabel();
        btnSetBoat = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        spinSlot = new javax.swing.JSpinner();

        setResizable(false);

        pnlBG.setBackground(new java.awt.Color(153, 153, 153));

        lblSetBoat.setText("Set Boat:");

        cBoxSetBoat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblInSlot.setText("In Slot:");

        btnSetBoat.setText("Set Boat");
        btnSetBoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetBoatActionPerformed(evt);
            }
        });

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        spinSlot.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        javax.swing.GroupLayout pnlBGLayout = new javax.swing.GroupLayout(pnlBG);
        pnlBG.setLayout(pnlBGLayout);
        pnlBGLayout.setHorizontalGroup(
            pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBGLayout.createSequentialGroup()
                        .addComponent(lblSetBoat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHelp))
                    .addGroup(pnlBGLayout.createSequentialGroup()
                        .addComponent(btnSetBoat)
                        .addGap(1, 85, Short.MAX_VALUE))
                    .addGroup(pnlBGLayout.createSequentialGroup()
                        .addGroup(pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cBoxSetBoat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBGLayout.setVerticalGroup(
            pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSetBoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBoxSetBoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSetBoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Populates the combBox by calling the database, returning a String array and setting the listModel of the combo box to that String array

    private void populateCBox() {
        DefaultComboBoxModel cbm = new DefaultComboBoxModel(db.getBoatsNotInTrailer(user));
        cBoxSetBoat.setModel(cbm);
    }

    //Grabs the info from the combo box and the spinWheel and uses that info to set the specified boat into the gui trailer
    private void btnSetBoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetBoatActionPerformed
        //Grabs the boat name from the comboBox
        String boatName = (String) cBoxSetBoat.getSelectedItem();
        //Grabs the slot number from the spinWheel
        int slot = (int) spinSlot.getValue();
        //Updates the database with the slot and boatName
        db.setBoatSlot(slot, boatName, user);
        //Updates the combo box with the boats not in the trailer
        populateCBox();
        //Visually clears the selected slot in the trailer gui
        dash.clearSlot(slot);
        //Visually updates the trialer gui with the boats now in the trailer
        dash.updateTrailer(user);
    }//GEN-LAST:event_btnSetBoatActionPerformed
    //Opens the help file
    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        try {
            File helpFile = new File("src/Resources/HTML/Help.html");
            Desktop.getDesktop().open(helpFile);
        } catch (IOException e) {
            System.out.println("Error\n" + e);
        }
    }//GEN-LAST:event_btnHelpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnSetBoat;
    private javax.swing.JComboBox cBoxSetBoat;
    private javax.swing.JLabel lblInSlot;
    private javax.swing.JLabel lblSetBoat;
    private javax.swing.JPanel pnlBG;
    private javax.swing.JSpinner spinSlot;
    // End of variables declaration//GEN-END:variables
}
